/** Curated Metro Manila + nearby spots for the matching engine. */

export const THEMES = {
  food: { id: "food", label: "Food & Eats" },
  trips: { id: "trips", label: "Short Trips" },
  travel: { id: "travel", label: "Off Country / Long Travel" },
  entertainment: { id: "entertainment", label: "Entertainment & Hangouts" },
};

export const PLACES = [
  {
    id: "poblacion-crawl",
    name: "Poblacion Weekend Crawl",
    area: "Makati",
    theme: "food",
    lat: 14.5652,
    lng: 121.0298,
    budget: "moderate",
    costPhp: 900,
    costLabel: "Around ₱800-1,200 each",
    rating: 4.6,
    walkable: true,
    group: "any",
    tags: ["bars", "food", "night", "friends"],
    blurb: "Tight cluster of restos and bars you can hop without a long commute.",
  },
  {
    id: "greenbelt",
    name: "Greenbelt Al Fresco",
    area: "Makati",
    theme: "food",
    lat: 14.5518,
    lng: 121.0216,
    budget: "splurge",
    costPhp: 1800,
    costLabel: "Around ₱1,500-2,500 each",
    rating: 4.7,
    walkable: true,
    group: "any",
    tags: ["mall", "fine dining", "park"],
    blurb: "Park-side dining with options from casual to a proper sit-down.",
  },
  {
    id: "mercato",
    name: "Mercato Centrale",
    area: "BGC",
    theme: "food",
    lat: 14.5503,
    lng: 121.0498,
    budget: "budget",
    costPhp: 450,
    costLabel: "Around ₱300-600 each",
    rating: 4.4,
    walkable: true,
    group: "large",
    tags: ["street food", "weekend", "squad"],
    blurb: "Open-air food stalls. Easy for a squad that wants variety without a reservation.",
  },
  {
    id: "binondo",
    name: "Binondo Food Walk",
    area: "Manila",
    theme: "food",
    lat: 14.6006,
    lng: 120.9744,
    budget: "budget",
    costPhp: 400,
    costLabel: "Around ₱250-500 each",
    rating: 4.8,
    walkable: true,
    group: "any",
    tags: ["chinese", "walk", "classic"],
    blurb: "Oldest Chinatown food stretch. Best on foot with a short list of must-tries.",
  },
  {
    id: "maginhawa",
    name: "Maginhawa Street Eats",
    area: "Quezon City",
    theme: "food",
    lat: 14.6449,
    lng: 121.0574,
    budget: "budget",
    costPhp: 350,
    costLabel: "Around ₱250-500 each",
    rating: 4.5,
    walkable: true,
    group: "any",
    tags: ["casual", "students", "cafes"],
    blurb: "Casual QC strip of restos, dessert spots, and late bites.",
  },
  {
    id: "tomas-morato",
    name: "Tomas Morato Dinner Strip",
    area: "Quezon City",
    theme: "food",
    lat: 14.6342,
    lng: 121.0345,
    budget: "moderate",
    costPhp: 850,
    costLabel: "Around ₱700-1,200 each",
    rating: 4.3,
    walkable: true,
    group: "any",
    tags: ["korean", "resto", "night"],
    blurb: "Long resto row. Good when the group cannot agree on one cuisine.",
  },
  {
    id: "legazpi-sunday",
    name: "Legazpi Sunday Market",
    area: "Makati",
    theme: "food",
    lat: 14.5536,
    lng: 121.0178,
    budget: "budget",
    costPhp: 300,
    costLabel: "Around ₱200-450 each",
    rating: 4.4,
    walkable: true,
    group: "any",
    tags: ["market", "weekend", "coffee"],
    blurb: "Sunday produce and ready-to-eat stalls beside the village park.",
  },
  {
    id: "karnivor",
    name: "BGC High Street Lunch",
    area: "BGC",
    theme: "food",
    lat: 14.5517,
    lng: 121.0526,
    budget: "moderate",
    costPhp: 750,
    costLabel: "Around ₱600-1,000 each",
    rating: 4.4,
    walkable: true,
    group: "any",
    tags: ["open air", "groups", "day"],
    blurb: "Wide sidewalks and plenty of tables. Easy meet-up point.",
  },
  {
    id: "intramuros",
    name: "Intramuros Walls Walk",
    area: "Manila",
    theme: "trips",
    lat: 14.5896,
    lng: 120.975,
    budget: "budget",
    costPhp: 200,
    costLabel: "Around ₱100-300 each",
    rating: 4.7,
    walkable: true,
    group: "any",
    tags: ["heritage", "walk", "history"],
    blurb: "Walled city loop. Bambike or walking both work for a short sponty.",
  },
  {
    id: "rizal-park",
    name: "Rizal Park Sunset",
    area: "Manila",
    theme: "trips",
    lat: 14.5832,
    lng: 120.9794,
    budget: "budget",
    costPhp: 0,
    costLabel: "Free to low-cost",
    rating: 4.3,
    walkable: true,
    group: "any",
    tags: ["park", "sunset", "open"],
    blurb: "Open lawns and a national-park scale walk without leaving the city.",
  },
  {
    id: "ayala-triangle",
    name: "Ayala Triangle Gardens",
    area: "Makati",
    theme: "trips",
    lat: 14.5564,
    lng: 121.0253,
    budget: "budget",
    costPhp: 150,
    costLabel: "Coffee money",
    rating: 4.5,
    walkable: true,
    group: "any",
    tags: ["park", "cbd", "lights"],
    blurb: "CBD pocket park. Strong for a reset between work and dinner.",
  },
  {
    id: "bgc-circuit",
    name: "BGC Park Circuit",
    area: "BGC",
    theme: "trips",
    lat: 14.5489,
    lng: 121.0562,
    budget: "budget",
    costPhp: 0,
    costLabel: "Free",
    rating: 4.6,
    walkable: true,
    group: "any",
    tags: ["run", "park", "day"],
    blurb: "Track, turf, and shade. Works for a walk, run, or picnic blanket.",
  },
  {
    id: "up-diliman",
    name: "UP Diliman Campus Loop",
    area: "Quezon City",
    theme: "trips",
    lat: 14.6538,
    lng: 121.0685,
    budget: "budget",
    costPhp: 100,
    costLabel: "Jeep + snacks",
    rating: 4.6,
    walkable: true,
    group: "any",
    tags: ["campus", "trees", "photo"],
    blurb: "Wide oval and academic core. Easy half-day with no tickets.",
  },
  {
    id: "antipolo",
    name: "Antipolo View Deck",
    area: "Rizal",
    theme: "trips",
    lat: 14.6255,
    lng: 121.1245,
    budget: "budget",
    costPhp: 400,
    costLabel: "Around ₱300-600 each",
    rating: 4.2,
    walkable: false,
    group: "any",
    tags: ["view", "pilgrimage", "short drive"],
    blurb: "Short drive east for a city-view pause and a shrine stop.",
  },
  {
    id: "circuit-makati",
    name: "Circuit Makati Grounds",
    area: "Makati",
    theme: "trips",
    lat: 14.5702,
    lng: 121.0174,
    budget: "moderate",
    costPhp: 600,
    costLabel: "Around ₱400-900 each",
    rating: 4.1,
    walkable: true,
    group: "any",
    tags: ["open space", "events"],
    blurb: "Former racetrack grounds. Check if a market or show is on.",
  },
  {
    id: "tagaytay",
    name: "Tagaytay Ridge Day Trip",
    area: "Cavite",
    theme: "travel",
    lat: 14.1153,
    lng: 120.9621,
    budget: "moderate",
    costPhp: 1500,
    costLabel: "Around ₱1,200-2,000 each",
    rating: 4.7,
    walkable: false,
    group: "any",
    tags: ["taal", "cool air", "day trip"],
    blurb: "Classic get-out-of-Manila ridge run. Vehicle required.",
  },
  {
    id: "enchanted-kingdom",
    name: "Enchanted Kingdom",
    area: "Santa Rosa",
    theme: "travel",
    lat: 14.2814,
    lng: 121.0955,
    budget: "splurge",
    costPhp: 2200,
    costLabel: "Around ₱1,800-2,800 each",
    rating: 4.4,
    walkable: false,
    group: "large",
    tags: ["theme park", "rides"],
    blurb: "Full-day park south of the metro. Better with a squad and a car.",
  },
  {
    id: "nuvali",
    name: "Nuvali Lakeside",
    area: "Santa Rosa",
    theme: "travel",
    lat: 14.239,
    lng: 121.058,
    budget: "moderate",
    costPhp: 900,
    costLabel: "Around ₱700-1,300 each",
    rating: 4.3,
    walkable: false,
    group: "any",
    tags: ["lake", "bike", "south"],
    blurb: "Planned township lakeside. Bike rentals and open space without going far south.",
  },
  {
    id: "laiya",
    name: "Laiya Beach Run",
    area: "Batangas",
    theme: "travel",
    lat: 13.6705,
    lng: 121.4062,
    budget: "splurge",
    costPhp: 3500,
    costLabel: "Around ₱2,500-4,500 each",
    rating: 4.5,
    walkable: false,
    group: "any",
    tags: ["beach", "overnight"],
    blurb: "South coast beach day. Treat as a long sponty, not a two-hour hop.",
  },
  {
    id: "subic",
    name: "Subic Bay Boardwalk",
    area: "Zambales",
    theme: "travel",
    lat: 14.7943,
    lng: 120.2714,
    budget: "moderate",
    costPhp: 1800,
    costLabel: "Around ₱1,400-2,400 each",
    rating: 4.4,
    walkable: false,
    group: "any",
    tags: ["bay", "duty free", "north"],
    blurb: "Northbound bay town. Works if the group is already in a vehicle.",
  },
  {
    id: "clark",
    name: "Clark Parade Grounds",
    area: "Pampanga",
    theme: "travel",
    lat: 15.185,
    lng: 120.56,
    budget: "moderate",
    costPhp: 1600,
    costLabel: "Around ₱1,200-2,200 each",
    rating: 4.3,
    walkable: false,
    group: "any",
    tags: ["north", "open", "airbase town"],
    blurb: "Wide former airbase town. Day trip if someone is driving north.",
  },
  {
    id: "moa",
    name: "MOA Eye & Seaside",
    area: "Pasay",
    theme: "entertainment",
    lat: 14.5352,
    lng: 120.9822,
    budget: "moderate",
    costPhp: 800,
    costLabel: "Around ₱600-1,200 each",
    rating: 4.4,
    walkable: true,
    group: "any",
    tags: ["mall", "ferris", "bay"],
    blurb: "Bay-side mall plus the Eye. Indoor backup if weather turns.",
  },
  {
    id: "bgc-highstreet-night",
    name: "High Street Night Hang",
    area: "BGC",
    theme: "entertainment",
    lat: 14.5512,
    lng: 121.0517,
    budget: "moderate",
    costPhp: 700,
    costLabel: "Around ₱500-1,000 each",
    rating: 4.5,
    walkable: true,
    group: "any",
    tags: ["open air", "lights", "hangout"],
    blurb: "Flat open park with nearby bars. Default BGC hang when nobody has a plan.",
  },
  {
    id: "eastwood",
    name: "Eastwood City Central",
    area: "Quezon City",
    theme: "entertainment",
    lat: 14.6091,
    lng: 121.0806,
    budget: "moderate",
    costPhp: 750,
    costLabel: "Around ₱500-1,100 each",
    rating: 4.2,
    walkable: true,
    group: "any",
    tags: ["cinema", "bars", "night"],
    blurb: "Cinema plus bars in one pocket. Easy for mixed energy groups.",
  },
  {
    id: "ortigas",
    name: "The Podium / Ortigas Hang",
    area: "Pasig",
    theme: "entertainment",
    lat: 14.5865,
    lng: 121.0614,
    budget: "moderate",
    costPhp: 850,
    costLabel: "Around ₱600-1,200 each",
    rating: 4.2,
    walkable: true,
    group: "any",
    tags: ["mall", "cinema", "cbd"],
    blurb: "Covered Ortigas option when rain or heat knocks out outdoor plans.",
  },
  {
    id: "qz-comedy",
    name: "Timog Comedy Night",
    area: "Quezon City",
    theme: "entertainment",
    lat: 14.6368,
    lng: 121.0349,
    budget: "budget",
    costPhp: 500,
    costLabel: "Around ₱350-700 each",
    rating: 4.4,
    walkable: true,
    group: "small",
    tags: ["comedy", "night", "sit down"],
    blurb: "Timog-Tomas pocket for stand-up and small venues. Check tonight's bill.",
  },
  {
    id: "arcade-bgc",
    name: "Timezone / Arcade Run",
    area: "Makati",
    theme: "entertainment",
    lat: 14.5478,
    lng: 121.0249,
    budget: "budget",
    costPhp: 400,
    costLabel: "Around ₱250-600 each",
    rating: 4.1,
    walkable: true,
    group: "any",
    tags: ["arcade", "indoor", "play"],
    blurb: "Indoor fallback. Works for mixed ages and rainy sponty nights.",
  },
  {
    id: "alabang-festival",
    name: "Festival Alabang Hang",
    area: "Muntinlupa",
    theme: "entertainment",
    lat: 14.4237,
    lng: 121.0318,
    budget: "moderate",
    costPhp: 700,
    costLabel: "Around ₱500-1,000 each",
    rating: 4.0,
    walkable: true,
    group: "any",
    tags: ["south", "mall", "cinema"],
    blurb: "South-side default if the pin is already below SLEX.",
  },
  {
    id: "national-museum",
    name: "National Museum Complex",
    area: "Manila",
    theme: "trips",
    lat: 14.5869,
    lng: 120.9812,
    budget: "budget",
    costPhp: 0,
    costLabel: "Free (check hours)",
    rating: 4.8,
    walkable: true,
    group: "any",
    tags: ["museum", "indoor", "culture"],
    blurb: "Fine Arts and Anthropology in one block. Strong indoor short trip.",
  },
  {
    id: "pampanga-sisig",
    name: "Angeles Food Detour",
    area: "Pampanga",
    theme: "food",
    lat: 15.144,
    lng: 120.589,
    budget: "moderate",
    costPhp: 800,
    costLabel: "Around ₱600-1,200 each",
    rating: 4.6,
    walkable: false,
    group: "any",
    tags: ["sisig", "north", "day trip"],
    blurb: "North food run. Only matches if the group is willing to leave the metro.",
  },
];
